# 爬虫工具的配置文件

# 爬虫抓取的版本
# 目前只有 1.7.10, 1.8.9, 1.9.4, 1.10.2, 1.11.2, 1.12, 1.12.2 七个可选（然而并没什么用）
version: 1.12.2

# 爬虫的线程数
threads_num: 20

# 爬虫的爬取的 mod 页数
mod_page: 35

# 爬虫爬取的 modpack 页数
# 这一处是专门下载 FTB 整合的，curse 上整合低端的太多，就用白名单了
modpack_page: 1

# 爬虫爬取 mod 的白名单，在此名单上的 mod 会被爬取
# 名单请使用 curseforge url 中的名称
mod_whitelist:
  - integrated-rest # 经典的集成动力学模组附属，支持网络通信
  - automated-redstone
  - inspirations
  - teletoro
  - simulated-nights
  - mrcrayfishs-device-mod # 家具模组作者的作品
  - mrcrayfishs-jumping-castle-mod # 家具模组作者的作品
  - dab-mod # 家具模组作者的作品
  - mrcrayfishs-vehicle-mod
  - angry-pixel-the-betweenlands-mod # 交错维度
  - taiga-tinkers-alloying-addon # 一个添加了很多合金的匠魂附属
  - techguns # 大名鼎鼎的科技枪
  - immersive-railroading # 沉浸铁路！太棒！
  - technomancy-2 # Noct943要求添加的模组
  - practical-logistics-2 # 实用物流拓展
  - bionisation-3 # Noct943要求添加的模组
  - rockhounding-mod-surface
  - rockhounding-mod-rocks
  - rockhounding-mod-core
  - rockhounding-mod-ore-tiers
  - rockhounding-mod-chemistry
  - autoverse # wz 钦点
  - hungryanimals
  - hungry-mechanics
  - compatskills
  - reskillable
  - thaumic-additions
  - improvable-skills
  - kitsus-forgecraft
  - quality-tools
  - potion-core
  - potioncraft
  - charcoal-pit
  - speedster-heroes
  - lucraft-core
  - thaumic-bases-unofficial
  - industrial-renewal
  - simpleoregen
  - extra-alchemy
  - improved-extraction
  - underground-biomes
  - torcherino
  - hooked
  - croparia
  - botania-tweaks
  - enderpay
  - dynamictrees
  - tetra
  - random-loot-mod
  - ic2-classic
  - compositegear
  - floodlights
  - largefluidtank
  - ezwastelands
  - birds-foods
  - embers-rekindled
  - pizzacraft
  - v0ids-smart-backpacks
  - roots-classic
  - vanillafoodpantry-mod
  - refraction
  - chunkpregenerator
  - scavenge
  - player-weight-mod
  - ender-rift
  - additional-enchanted-miner
  - camera-obscura # 好模组
  - the-camping-mod # 露营模组，很有趣
  - tinkers-arsenal
  - tinkers-aether
  - good-ol-currency
  - pams-weee-flowers
  - immersivemusic
  - zaraklib
  - multibags
  - asmodeuscore
  - galaxy-space-addon-for-galacticraft
  - equivalent-additions
  - ftb-quests
  - black-hole-storage
  - from-the-ground-up
  - equivalent-energistics
  - abyssalcraft-heads
  - simple-underground-biomes
  - moar-boats
  - patchouli
  - natures-aura
  - random-psideas
  - simply-platinum # 玩家反馈的意味不明模组
  - cofh-vanilla-satchels
  - moreplates
  - tinkers-forging
  - derfl007s-road-mod
  - rails-of-war
  - integrated-terminals
  - integrated-crafting
  - harder-ores
  - ore-flowers
  - harder-farming
  - expanded-industry
  - millenaire # 千年村庄（Millénaire）
  - better-diving
  - auraddons

# 爬虫爬取 modpack 白名单，在此名单上的 modpack 会被爬取
# 仅适用于 curseforge 整合
# 名单请使用 curseforge url 中的名称
modpack_whitelist:
  - all-the-mods-3
  - modern-skyblock-3-departed
  - forever-stranded-lost-souls
  - sevtech-ages
  - exoria
  - stoneblock
  - gregblock
  - project-ozone-3-a-new-way-forward
  - enigmatica2expert
  - enigmatica2
  - ultimate-alchemy
  - skyfactory-4

# 爬虫爬取 mod 的黑名单，在此名单上的模组会被禁止爬取，会覆盖白名单
# 名单请使用 curseforge url 中的名称
mod_blacklist:
  - dungeon-tactics # 乱码
  - minecraft-comes-alive-mca # 无意义人名翻译
  - mike-dongles # 无意义粉丝向模组
  - magical-psi # 仅仅改材质，但是作者忘记删语言文件了
  - the-twilight-forest # 目前有他人对此翻译存在反对观点，暂时列为黑名单，规避冲突
  - charset-lib # 3TUSK 指出不需要翻译
  - forestry # 3T维护
  - metamorph # horsewithnoname 的模组
  - aperture # horsewithnoname 的模组
  - blockbuster # horsewithnoname 的模组
  - imaginary # horsewithnoname 的模组
  - greenscreen
  - slashblade # 翻译问题较多，目前上传了固定版本，不再变动
  - the-aether-ii
  - extraplanets # 岩浆水覆盖问题
  - shetiphiancore # 染料颜色重名问题
  - skillable # 原作者不在更新
  - smarthoppers-mod # 太过抽象
  - thaumic-equivalence # 缺失翻译最多的手册部分目前还未实装
  - embers # 已经不再维护
  - ice-and-fire-dragons # EEEEEET
  - projecte #手册暂时有问题
  - lycanites-mobs
  - gregblock-utilities # 这个作者干了一件很有趣的事情，把自己模组的 domain 和 gtce 弄成一样的
  - gregic-additions # 同上
  - craftpresence # 汉化会导致崩溃，是的
  - ender-io-base # 下面的东西居然和 enderio 使用了相同的 assets domain，导致翻译会被覆盖
  - ender-io-machines
  - ender-io-conduits
  - ender-io-endergy
  - ender-io-inventory-panel
  - ender-io-ae2-conduits
  - ender-io-oc-conduits
  - ender-io-rs-conduits
  - ender-io-forestry
  - ender-io-tic
  - ender-io-zoo
  - simple-tcon
  - anger-management
  - land-craft # 过于抽象
  - landcore # 过于抽象
  - twitch-chat-integration # 有加载 Bug
  - lord-craft # 过于抽象
  - chineseworkshop # 自带中文
  - not-enough-roofs # 自动生成的语言文件

# 爬虫爬取 modpack 黑名单，在此名单上的整合包会被禁止爬取，会覆盖白名单
# 名单请使用 curseforge url 中的名称
modpack_blacklist:
  - the-new-frontier # 这个整合会莫名其妙不存在文件

# del list 名单，用于清除不需要提交的 assets 文件
# 需要写入对应的 assets 文件名，不是 url 名称
del_list:
  - writing_guides
  - chisel_guide # 凿子 mod 的手册，无需翻译
  - pokecube_books # pokecube 模组手册，乱码无法翻译
  - bloodmagicguide # 血魔法手册，无需翻译
  - evilcraftcompat # 附带在 EvilCraft 内的兼容性 mod，无语言文件
  - torohealthmod # ToroHealth Damage Indicators 血量显示 mod，无语言文件
  - packmode # 无语言文件
  - shulkerbox # Advanced Shulkerboxes，一个可以在背包直接打开潜影盒的 mod，无语言文件
  - progressivebosses # 错误编码
  - jaopca # 会导致崩溃
  - tinkersdefense # 新版本已经修改名称，这个名称属于旧版本残留，删去
  - simpleautorun # 空语言文件
  - equipmenttooltips # 空语言文件
  - defiled-lands # 瞎编乱造词语
  - lordcraft
  - landcraft
  - landcore
  - angermanagement
  - kk
  - xtones

# 某些英文键不是我们想要的，可以通过这一块书写删除它
del_key:
  - 'msg.entity.rocket.seldst'
  - 'commands.reload.usage'
  - 'tile.freezer.name'
  - 'tile.mirror.name'
  - 'name.TRINKET'
  - 'tile.oreIron.name'
  # 下面四个是 Railcraft 对原版铁轨名字的修改
  - 'tile.activatorRail.name'
  - 'tile.detectorRail.name'
  - 'tile.goldenRail.name'
  - 'tile.rail.name'
